// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Base defaults (fallback)
const SUPABASE_URL = "https://eslcxgomsaizesekdvcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbGN4Z29tc2FpemVzZWtkdmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODQ4ODAsImV4cCI6MjA2ODk2MDg4MH0.1MeKBV8__kEK06kOlj9VlNnLwtm9BWJfOv_dLlnNRnM";

// Allow runtime overrides via localStorage or global window variables
const resolvedUrl =
  (typeof localStorage !== 'undefined' && localStorage.getItem('supabase_url')) ||
  (globalThis as any).__SUPABASE_URL__ ||
  SUPABASE_URL;

const resolvedAnonKey =
  (typeof localStorage !== 'undefined' && localStorage.getItem('supabase_anon')) ||
  (globalThis as any).__SUPABASE_ANON_KEY__ ||
  SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(resolvedUrl, resolvedAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});